Fix QRadialGradient TypeError in spotlight effect
Fixed incorrect usage of QRadialGradient constructor that was causing:
TypeError: 'colorAt0' is an unknown keyword argument

Changed from using invalid keyword arguments to properly creating the gradient
and setting colors with setColorAt() method.